### ISSUE TITLE
Additional protocol decode data

### ISSUE THREAD

**Issue by Numbski** [micampe/mel-heatpump-homekit#2]
Just a head's up that on the SwiCago project, there's a decent thread on decoding protocol.

https://github.com/SwiCago/HeatPump/issues/39#issuecomment-854479240

Also relevant:

https://github.com/m000c400/Mitsubishi-CN105-Protocol-Decode

**Comment by micampe** [comment]
Hi Tony, sorry for the late reply but unfortunately I have now moved to a new house (with is the main reason for the delay) with different AC units so I’m not using this code anymore so I won’t be able to maintain it further.
